### ISSUE TITLE
Is it possible to embed the animation?

### ISSUE THREAD

**Issue by cbeust** [cubing/alg.cubing.net#141]
I'd like to embed an animation (e.g. animated GIF or whatever makes the most sense) of a given algorithm in my own site.

**Comment by lgarron** [comment]
https://alg.cubing.net/?alg=R_U_R-_U-_R-_F_R2_U-_R-_U-_R_U_R-_F-&type=alg&title=T-Perm&view=playback can easily be placed in an iframe. Do you need something else?

**Comment by cbeust** [comment]
On a page with sometimes dozens of these algorithms, it's not really realistic to create as many iframes.

**Comment by lgarron** [comment]
Yeah, frames are not great. I'm working on making twisty.js easy to use many times on a page, but I'm afraid I can't offer a timeline for that yet. You may want to look into using Roofpig for now.

(I'll close this issue since there is no separate task it's tracking. Feel free to ask more questions here if you'd like.)
