### ISSUE TITLE
Please add a new color scheme

### ISSUE THREAD

**Issue by lihaoyu1234** [cubing/alg.cubing.net#166]
In the WCA Regulations, the standard color scheme is the white face on the top and the green face on the front (BOY, `grobyw`). But in most CFOP tutorials, the color scheme is the yellow face on the top and the red face on the front (`rgbowy`). This is also a common placement scheme. But there is no such color scheme in the preset color scheme of acn (alg.cubing.net). At this time, we need to use a custom color scheme, but doing so every time we use it can be cumbersome. So could you consider adding this color scheme to the preset color scheme?

**Comment by lgarron** [comment]
`alg.cubing.net` development is frozen, but I'm actively thinking about this for Twizzle. This is a bit more complicated than it might seem, because often people ask for one thing but really are asking for something more specific or more general — in your case, it sounds like it matters to you to reorient the puzzle than to have a "new color scheme"?

To that end, how helpful would it be to have a way to have yellow on top for CFOP steps, but no control over what color is in front? I'm hoping that such an option makes it easy to support most important use cases without having to support something much more complicated at the same time.


https://github.com/cubing/cubing.js/issues/157
